# TODO: sdl_mixer is not found for linux, vlc for mac
# TODO: run the minimal test also from the installed gemrb
language: cpp

dist: xenial
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cmake
    - libpython2.7
    - zlib1g
    - zlib1g-dev
    - libsdl1.2debian
    - libsdl1.2-dev
    - libopenal1
    - libopenal-dev
    - libsdl-mixer1.2
    - libsdl-mixer1.2-dev
    - libfreetype6
    - libfreetype6-dev
    - libvlc-dev
    - libvlccore-dev
    - libpng12-0
    - libpng12-dev
    - libvorbis0a
    - libvorbis-dev
    - openssh-client
    - python-dev
  ssh_known_hosts: frs.sourceforge.net

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl openal-soft freetype sdl_mixer libpng libvorbis; fi
  - touch id_travissfbot
  - if [[ $TRAVIS_SECURE_ENV_VARS == "true" ]]; then openssl aes-256-cbc -K $encrypted_d3cf1349d561_key -iv $encrypted_d3cf1349d561_iv -in testing/id_travissfbot.enc -out id_travissfbot -d; fi
  - chmod 0600 id_travissfbot

before_script:
  - cmake --version

script:
  - |
    mkdir build && cd build &&
    if [ $TRAVIS_OS_NAME != osx ]; then
      static="-DSTATIC_LINK=1 -DLAYOUT=home"
    fi &&
    cmake -DCMAKE_INSTALL_PREFIX=iprefix $static .. &&
    make &&
    if [ $TRAVIS_OS_NAME != osx ]; then
      sed -i '1 a \ AudioDriver = none' ../gemrb/GemRB.cfg.noinstall.sample &&
      gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample
    fi &&
    make install

deploy:
  provider: script
  edge: true
  script: ../testing/travis-deploy.sh
  on:
    branch: master
    condition: $CC == clang

notifications:
  email:
    on_success: never
    on_failure: change
  irc:
    channels:
      -  "irc.freenode.org#gemrb"
    on_success: never
    on_failure: change

os:
  - linux
  - osx

jobs:
  exclude:
    - os: osx
      compiler: gcc # actually just linked to clang
